### ISSUE TITLE
Argument 3 passed to …

### ISSUE THREAD

**Issue by itsmylife44** [Paisseon/Satella#1]
Hello . 

I am actually on iPhone 7 ios 14.6 checkra1n

![15BB2496-B896-426D-A8C6-3DA0E9E96C44](https://user-images.githubusercontent.com/34112129/152495130-a80ec70a-faac-44ad-a962-c7b39a9b0d65.jpeg)

**Comment by Paisseon** [comment]
0.4b should fix this. Thanks for the report :)
