### ISSUE TITLE
how did you learn to create tweak ?

### ISSUE THREAD

**Issue by dualra1n** [Paisseon/Satella#10]
sorry that is not an issue however I want to become a creator tweak and learn how programming tweaks with swift or objective c :)
I am too young like you so I wait for your help

**Comment by Paisseon** [comment]
Mostly through seeing what other people (mostly Litten) have done and trying to figure out how it works, and also using the Flex 3 Beta tool. Although I'm trying to learn app development now and that's probably a better place to start.

A nice starting place for Swift is https://hackingwithswift.com/100
and for Objective-C is https://www.binpress.com/learn-objective-c-24-days

**Comment by dualra1n** [comment]
oh, interesting thanks my bro

**Comment by dualra1n** [comment]
hihi my sister xd
