### ISSUE TITLE
SatellaPrefs.bundle

### ISSUE THREAD

**Issue by yubef** [Paisseon/Satella#11]
i got this error on ipad air 3, ios 13.3.1 Satella ver 1.3.2, how can i solve this? thanks
![image](https://user-images.githubusercontent.com/117343714/199669552-7cc7c812-3035-46ed-9cff-49381fe2bdb4.png)

**Comment by Paisseon** [comment]
Does it work with the "TweakSettings" tool from CyPwn repo?

**Comment by yubef** [comment]
yes it does thanks so much
![image](https://user-images.githubusercontent.com/117343714/200446172-9a8c7047-7e01-4e95-9346-514603dcb39a.png)
