### ISSUE TITLE
HI, about support ios 15

### ISSUE THREAD

**Issue by dualra1n** [Paisseon/Satella#12]
hey, I tried to install satella2 on ios 15.7 and satella2 does not work however vivy work very well, vivy is very beautiful nice work. so orion 12-14 works correctly. I told you that in case you want to know about that. 
![ac427338-94f4-48b0-a8b9-fcc37e83809b](https://user-images.githubusercontent.com/85508740/202051300-4b2443b4-e663-495c-9ed9-2f250ce1e4cd.jpg)

**Comment by dualra1n** [comment]
@Paisseon

**Comment by Paisseon** [comment]
Satella doesn't use Orion any more so that wouldn't be the issue. Have you tried it on an app that works for sure like Fight Club 5?

**Comment by dualra1n** [comment]
yes that work however a lot of other app does not work

**Comment by dualra1n** [comment]
quick question, what do you use to inject swfit code? because the only tool that i know is orion

**Comment by Paisseon** [comment]
If it works on any app, that just means the other apps aren't compatible and is unlikely to be an iOS 15 issue. As for injecting Swift code, I'm using [Jinx](https://github.com/Paisseon/Jinx)

**Comment by dualra1n** [comment]
nice

**Comment by dualra1n** [comment]
@Paisseon if you have any sdk of ios 15 to use with theos, could you share to me, please
