### ISSUE TITLE
Crash on 1.4.2

### ISSUE THREAD

**Issue by Ectalite** [Paisseon/Satella#14]
Hi, I updated to 1.4.2 yesterday and it made Plex crash.
After I reverted back to 1.4.1, Plex was working. 
Here is the crashlog:
[Crashlog.txt](https://github.com/Paisseon/Satella2/files/10238454/Crashlog.txt)

**Comment by Paisseon** [comment]
Does it crash if the Receipt toggle is disabled?

**Comment by Ectalite** [comment]
Sorry for the late response.
Deactivating the receipts option does fix the crash issue.
