### ISSUE TITLE
Satella 1.6 Crash (iPhone 8 Plus 16.1.2,Palera1n)

### ISSUE THREAD

**Issue by TGDelz** [Paisseon/Satella#19]
Crashes most App at Launch, Doesn’t Work at the momment

**Comment by Paisseon** [comment]
Known issue. It's a bug with the preferences IPC server

**Comment by Paisseon** [comment]
Removing "Jinx IPC Server" and installing Satella 1.5 fixes

**Comment by Paisseon** [comment]
Fixed in 1.7 and newer
