### ISSUE TITLE
No Working

### ISSUE THREAD

**Issue by doimty** [Paisseon/Satella#22]
iDevice: iPhone 11
iOS: 13.6
Jailbreak: Odyssey 1.4.2
Satella version: 1.7.1
![image](https://user-images.githubusercontent.com/78968666/228149328-ca5bb345-b2b6-4baf-ad3c-51312ec9c899.png)
![image](https://user-images.githubusercontent.com/78968666/228149710-2fdb12f8-f282-4549-add1-65d73b4ba0ef.jpeg)

**Comment by svenn39** [comment]
I also have this

**Comment by Paisseon** [comment]
Try 1.8.1, should be fixed
