### ISSUE TITLE
Partially working (BatteryLife)

### ISSUE THREAD

**Issue by SethWiiPlaza** [Paisseon/Satella#25]
![image](https://github.com/Paisseon/Satella/assets/8001327/e62047cd-f670-4d6d-be8e-df1c135ab874)![image](https://github.com/Paisseon/Satella/assets/8001327/e50bc57e-caa3-4a50-8554-7123fabab6d5)

**com.rbtdigital.Battery-Life
AppStore Version 23.1.4

**

**Comment by Paisseon** [comment]
Server-sided.
