### ISSUE TITLE
Satella2 does not work in "Land & Castles" and "Don't get fired!" games

### ISSUE THREAD

**Issue by eoyoa** [Paisseon/Satella#3]
# Device Information
Device: iPhone 11 Pro
iOS Version: 14.4
Jailbreak: Unc0ver w/ Fugu14

# Tweak Information
Satella2 settings:
> Enable: TRUE
> Receipts: TRUE
> Observer: TRUE
> Global injection: TRUE

Installed Satella2 using Zebra. Using Orion Runtime (iOS 14) as a replacement for dependency Orion (iOS 12-13).

Satella2 works for Apollo Tip Jar purchases and Retro Bowl IAPs.

# Issues
Clicking "Unlock" in Land & Castles game (https://apps.apple.com/us/app/land-and-castles/id1493287599) fails to fake-purchase the full unlocked game.

Attempting to buy any in-app purchase in "Don't get fired!" game (https://apps.apple.com/us/app/dont-get-fired/id1008957297) fails with no effect.

**Comment by Paisseon** [comment]
Are you able to hack them using LocalIAPStore? Many apps aren't compatible

**Comment by eoyoa** [comment]
> Are you able to hack them using LocalIAPStore? Many apps aren't compatible

No, LocalIAPStore does not work. I guess those apps are just incompatible.
