### ISSUE TITLE
Game crash from nil

### ISSUE THREAD

**Issue by TrevorCow** [Paisseon/Satella#5]
# Device Information
Device: iPad Pro (11-inch) (2nd generation) and iPhone 13 Pro max
iOS Version: 14.3 and 15.0.2 respectively 
Jailbreak: Taurine on iPad, iPhone 13 pro max is jailed

# Issue
When trying to inject into the game "Pocket-Run", the app crashes with reason `-[__NSCFString appendString:]: nil argument`. On the jailbroken iPad this doesn't happen until you try to make a purchase but on the jailed iPhone with SatellaJailed it happens on launch.

Doesn't seem like Stella's fault (I can't seem to find any calls to appendString in Stella but I'm no expert in iOS nor tweak development) but wondering if there is a reason and possible fix.

# CrashLogs

iPad Cr4shed report attached
[iPadPocketRunCr4ashed.txt](https://github.com/Paisseon/Satella2/files/8259769/iPadPocketRunCr4ashed.txt)

iPhone crash log from console
```
Uncaught exception: NSInvalidArgumentException: -[__NSCFString appendString:]: nil argument
(
	0   CoreFoundation                      0x0000000180720070 6174789A-E88C-3F5C-BA39-DE2E9EDC0750 + 626800
	1   libobjc.A.dylib                     0x0000000198c3af54 objc_exception_throw + 60
	2   CoreFoundation                      0x0000000180829538 6174789A-E88C-3F5C-BA39-DE2E9EDC0750 + 1713464
	3   CoreFoundation                      0x00000001807c5520 6174789A-E88C-3F5C-BA39-DE2E9EDC0750 + 1303840
	4   CoreFoundation                      0x00000001806a40d4 CFRelease + 0
	5   Pocket-Run                          0x0000000102c63394 Pocket-Run + 1438612
	6   Satella.dylib                       0x00000001059aa838 Satella.dylib + 26680
	7   StoreKit                            0x00000001a44f99d8 E6970DDA-D23E-3AFA-8765-C5829B22BFDE + 14808
	8   libdispatch.dylib                   0x0000000180390c04 959CD6E4-0CE7-3022-B73C-8B36F79F4745 + 7172
	9   libdispatch.dylib                   0x0000000180392950 959CD6E4-0CE7-3022
```

**Comment by Paisseon** [comment]
My first thought is the receipt generator's string interpolation might use appendString internally. I should probably check for all the fields to not be nil before using so I'll add that. 

In the mean time, disabling Receipts in Satella 2 prefs may fix on your jailbroken iPad if I am correct— I'm also working on in-app preferences for Satella Jailed but that will take longer

**Comment by TrevorCow** [comment]
I thought it might have been that because that's the only place I saw lots of string-related functions, however, since I was on iOS 14 I already had Receipts generation disabled. I also tried with observer and bypass toggled on and off and it still happens. Does the receipt code still fire even if receipts are disabled?

**Comment by TrevorCow** [comment]
I realized I was actually running the old Satella 1 (because it was version 2.8.1 vs Satella 2 version 1.0.1) that's my bad, but now the crash still happens but only when receipts are DISABLED. With receipts on it just doesn't work and receipts off it crashed with the same error as before. It also still happens in the jailed version.

**Comment by Paisseon** [comment]
Can you send me a decrypted .ipa for Pocket-Run so I can use it for testing? It doesn't seem to be on the App Store in my country

**Comment by TrevorCow** [comment]
Github wouldn't let me upload it so here it is on google drive.
https://drive.google.com/file/d/14iyKdP5rPTyuVcocQ8VBN1v-othfeXLg/view?usp=sharing

**Comment by Paisseon** [comment]
I think I figured it out. The problem is with the Sideloaded compatibility. I did a couple things and I'm not sure which one fixed, but it's working now. 1.0.2 out in a couple minutes

**Comment by Paisseon** [comment]
Oh, and I'm also going to add the fix to Jailed
