### ISSUE TITLE
not working at all

### ISSUE THREAD

**Issue by amarildomoney** [Paisseon/Satella#7]
i’m on ios 14.3 iphone 8, using taurine jailbreak.
 tried with multiple games and apps, nothing seems to work

**Comment by Paisseon** [comment]
1. Is the price 0,00?
2. Is Global Injection or the individual app injection enabled?

**Comment by amarildomoney** [comment]
> 

global injection enabled, and yes the price is 0,00 on all apps/games.

**Comment by Paisseon** [comment]
Ok, so it's injecting. Does it work if you try on the app Game Master 5?

**Comment by amarildomoney** [comment]
i tried with global injection on, it worked!.

**Comment by Paisseon** [comment]
Probably just the other apps are server sided then 🤷‍♀️

**Comment by amarildomoney** [comment]
i also have iosgods’s iap cracker and for some apps it works, for example pocket mortys but, when i tried with satella it doesn’t worked.
