### ISSUE TITLE
Craft Crack

### ISSUE THREAD

**Issue by Isaac7u7** [Paisseon/Satella#8]
Hi, I don't know how to send you an request, but do you can check out this app to see if it's possible to crack it?
It's called craft:

https://apps.apple.com/mx/app/craft-docs-y-editor-de-notas/id1487937127

Thank you!

**Comment by Paisseon** [comment]
[emt.paisseon.craft_1.0_iphoneos-arm.deb.zip](https://github.com/Paisseon/Satella2/files/9227068/emt.paisseon.craft_1.0_iphoneos-arm.deb.zip)

It won't raise the storage limit (that's hosted on their server, can't do shit client-side) but exporting in various formats, in-document searching, etc. are available

**Comment by Isaac7u7** [comment]
Thank you! Worked! 
Just a question; how can I change the profile picture? It always change it back 😅 to the yours👀

**Comment by Paisseon** [comment]
[emt.paisseon.craft_1.0_iphoneos-arm.deb.zip](https://github.com/Paisseon/Satella2/files/9227612/emt.paisseon.craft_1.0_iphoneos-arm.deb.zip)

**Comment by Paisseon** [comment]
Fixed ^

**Comment by Isaac7u7** [comment]
Thanks a lot! I like a lot to write so I'll be happy to use this app now. ❤️
Just a last question; the app VSCO Cam could be cracked too?:) 

https://apps.apple.com/pl/app/vsco-photo-video-editor/id588013838

Thank you again!
